### ISSUE TITLE
running the minimal demo on OSX, there is no window visiable

### ISSUE THREAD

**Issue by tephyrnex** [sciter-sdk/pysciter#15]
running the minimal demo on OSX, there is no window visiable

**Comment by pravic** [comment]
Sciter version?
Can you run usciter/uminimal from its sdk?

**Comment by tephyrnex** [comment]
I had to go into the .app folder and change the permissions to allow execute, but yes, I can run all files within sciter-sdk/bin.osx

**Comment by pravic** [comment]
Well, unfortunately it's quiet complicated for me to test something under OSX right now. May be @midiway would help.

**Comment by midiway** [comment]
yep, tested, and the problem really occurs
I am don't program in Python, but at looking at the code here:
https://github.com/sciter-sdk/pysciter/blob/master/examples/minimal.py#L6
I think it needs to specify the window size..
But I dont know the Python syntax...

**Comment by pravic** [comment]
Thanks, you are right.

**Comment by tephyrnex** [comment]
changing line 6 fixes it
    frame = sciter.Window(ismain=True, uni_theme=True, size=[800,600])

**Comment by pravic** [comment]
Sorry, I forgot to upload a fixed version to PyPi. It creates window with default size if this parameter was not given.

You can update it now by running `pip install pysciter --upgrade`.
