### ISSUE TITLE
Dialog position on (Linux)

### ISSUE THREAD

**Issue by italozaina** [sciter-sdk/pysciter#18]
* It's not working the position of dialogs or msgbox on linux. 
* Always open on **top-left** (0:0) of screen.

![captura de tela de 2018-05-27 19-21-26](https://user-images.githubusercontent.com/10713452/40591203-315b7894-61e3-11e8-93c4-3ae526a37c18.png)

**Comment by pravic** [comment]
True. However, better to report on https://sciter.com/forums/forum/bug-reports/ about such things.

I'll close this one.

**Comment by pravic** [comment]
I've posted it for you: https://sciter.com/forums/topic/linux-dialog-position/

**Comment by italozaina** [comment]
Thank you for the answer and sorry for report on wrong place
