### ISSUE TITLE
Input[type=number] missing method

### ISSUE THREAD

**Issue by italozaina** [sciter-sdk/pysciter#19]
doSelectAll()

Only work when i  change my input to text

**Comment by pravic** [comment]
I can't see any methods on this page: https://sciter.com/docs/content/behaviors/number.htm

Anyway, such a question belongs to http://sciter.com/forums. This issue tracker regards to Python bindings itself.

**Comment by pravic** [comment]
> Only work when i change my input to text

Yes, because only [`behavior:edit`](https://sciter.com/docs/content/behaviors/edit.htm) has such methods. I don't know why, so better ask on Sciter forums.

**Comment by italozaina** [comment]
Perfect, it's exactly i was looking for.

Thank You !!!
