### ISSUE TITLE
Instructions to build for raspberry pi / headless mode (sciter lite?)

### ISSUE THREAD

**Issue by martinlombana** [sciter-sdk/pysciter#28]
Hi, 

I am looking for instructions on how to build, using pysciter and pyinstaller, for the raspberry pi in headless mode (with sciter lite, I believe). My aim is to produce a single linux binary, where I will control HTML and CSS with python. I have built in windows, with pysintaller, and regular sciter.dll, and it works but I am a bit lost when it comes to the raspberry pi / linux creation targeting sciterlite. I want to evaluate the use of sciter por Kiosk UI-s with keyboard input and also touch input. 

Moreover, I don't know if with the current bindings, I could use or call from python (even if they are not done yet) all the graphic functions. My aim is to avoid JS/Tisscript, as I want to keep everything in Python and manipulate the DOM and graphics with python. In this regard, I don't know if there is a performance penalty for doing it this way, or not really because, anyway, _tiscript_ would also be calling native C++/C functions. If you could clarify I would be grateful!

Thanks,

**Comment by pravic** [comment]
cc @c-smile

**Comment by pravic** [comment]
However, such questions related to Sciter itself rather than bindings - better to ask on sciter.com/forums/

**Comment by martinlombana** [comment]
@pravic , I will ask in the forum! Sorry about it. Closing this "non issue". Thanks!
