### ISSUE TITLE
Sciter.JS Support?

### ISSUE THREAD

**Issue by AlecHaring** [sciter-sdk/pysciter#39]
I prefer JS over TIScript so, just for the hell of it, I swapped out the normal Sciter SDK bin for the Sciter.JS SDK bin and to my surprise, PySciter was able to open a frame and load an HTML file with some JavaScript! It seems like most stuff works right out of the box, but some stuff causes segmentation faults (have yet to figure out what) and functions like on_debug_output output '[object]' as the error message instead of the actual message:
![Screen Shot 2021-03-30 at 11 27 04 PM](https://user-images.githubusercontent.com/19616756/113086345-726d4480-91af-11eb-9d09-bd5f77c80020.png)
It seems like most problems arise when debug mode is enabled.

How hard would it be to implement support for the Sciter.JS SDK? Forgive me if this is a stupid question as I am not super familiar with the inner workings of the Sciter SDK or PyScitter yet. I'm just curious if it's something worth delving into and if anyone has a recommendation as to where I should start.

Thanks!

**Comment by pravic** [comment]
Hey.
According to this: https://github.com/c-smile/sciter-js-sdk/discussions/56 Sciter and Sciter.JS are compatible (or it should be so). If not, it's on the SDK's side.

Sciter.JS is relatively young, so expect some roughness.

**Comment by AlecHaring** [comment]
Hmm, interesting. It might be a problem on my end then. I was under the impression that they were not meant to work together which was why I assumed the issues I was having were compatibility related.

Thanks for the help!
