### ISSUE TITLE
don't can use import 

### ISSUE THREAD

**Issue by kingtelepuz5** [sciter-sdk/pysciter#44]
ImportError: libsciter-gtk.so was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) are available in the path.
libsciter-gtk.so: cannot open shared object file: No such file or directory
libsciter-gtk-64.so: cannot open shared object file: No such file or directory

ubuntu 20.04 

i am dowloand SDK but don't understand now to use and  what i am need to do it 
please help 
path to bin 
~/sciter-js-sdk/bin

**Comment by pravic** [comment]
```bash
export ~/sciter-js-sdk/bin/linux/x64
```

**Comment by pravic** [comment]
In terminal, of course. To fix that "libsciter-gtk.so was not found" error.

**Comment by kingtelepuz5** [comment]
okay, i am unintall SDK, and install again, so later i say what i do and what i have, thx to feedback
