### ISSUE TITLE
Cannot load dll

### ISSUE THREAD

**Issue by MrSassyBritches** [sciter-sdk/pysciter#46]
OS: Windows 10
Sciter: v4.4.8.0 (JS)
Pysciter: v0.5.1

Path to Sciter-SDK: `%USERPROFILE%\.sciter` (this is the exact string in my User-PATH variable.

Hello! I am unable to get my sciter app to run. I have downloaded and unzipped the Sciter-JS-SDK to the location mentioned above. I have also added this to my User Path in the enviroment variables just I like I have done with Python, Rust, Go, Chocolatey, etc... But I cannot run my application.

```
import sciter
if __name__ == "__main__":
    sciter.runtime_features(file_io=True, allow_sysinfo=True)

    frame = sciter.Window(ismain=True, uni_theme=True)
    frame.load_file("index.html")
    frame.run_app()

```
This gives me the error:

```
ImportError: sciter.dll was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) are available in the path.
'sciter': Could not find module 'sciter' (or one of its dependencies). Try using the full path with constructor syntax.
'sciter64.dll': Could not find module 'sciter64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

I have done things like:

- copy/paste `sciter.dll` to `sciter64.dll` so both are in the path.
- installed PythonNet and pywin32 as these are common to need for Windows development.
- Add `sciter.dll` and `sciter64.dll` to my root project directory, virtual environment, System PATH, and even just into my `C:` directory.
- I have also done ALL of the above with the Sciter-TI-SDK. I did this because the last time I successfully ran a PySciter project I used TI Script several years ago. 

So...
1) In case I have my path configured incorrectly, what does YOURS look like so I can try to fix mine.
2) Does PySciter know or care if I use the JS or TI SDK? Should I use a specific version of the SDK? 
3) Are there dependencies I should be aware of that I happen to have missed when reading the setup documentation for either Sciter and/or PySciter?

Any help or insight into this matter would be greatly appreciated, thank you :)

**Comment by 8ctopus** [comment]
I had the same issue and fixed it by using the 64 bit `sciter.dll`.
