### ISSUE TITLE
Does PySciter support sciter. Js？

### ISSUE THREAD

**Issue by ylm-king** [sciter-sdk/pysciter#50]
## Question 
- [ ] If so, what should I do
- [ ] If not, will you support it in the future
- [ ] If not, is there an alternative

## Please reply to the question, thank you

**Comment by pravic** [comment]
It does, API is the same. Look at the Sciter.JS examples.

However, I probably need to create an example as well.

**Comment by ylm-king** [comment]
### 我知道是 那个 sciter.dll 问题，
- Using sciter. DLL in sciter. Js disables tiscript  
- Using the sciter. DLL in the sciter- JDK, the script is invalid 
### Is there a way to run both scripts simultaneously

**Comment by pravic** [comment]
Simultaneously - of course, not. Either TiS or JS.
Why do you need it?

**Comment by ylm-king** [comment]
I want to use some of the usual JS frameworks

**Comment by pravic** [comment]
Well, you have to use them with TypeScript or JavaScript.
Or you have to port them to TIScript.

No other options.
