### ISSUE TITLE
A problem combining pysciter with wxPython through WindowProc

### ISSUE THREAD

**Issue by zelid** [sciter-sdk/pysciter#9]
There is a problem combining `pysciter` and `wxPython`

I'm on win32-python-3.4.4 and installed `pysciter` from pip and `wxPython` from pip using this command: 
`pip install --upgrade  --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix`

pysciter has an example of hooking to WindowProc:
https://github.com/pravic/pysciter/blob/master/examples/plain-win.py

wxPython has an example of giving access to WindowProc:
https://wiki.wxpython.org/HookingTheWndProc

I tried to combine both:
https://gist.github.com/zelid/831d8e59d5bbe86324aa056ffe3cbb5d
, but it doesn't show the expected content of `minimal.htm`

What do I do wrong?

**Comment by pravic** [comment]
No idea what's wrong at first view.

You can look at [sciter-wxwidgets-sample](https://github.com/pravic/sciter-wxwidgets-sample), it use slightly another way, by creating a child window for Sciter. May be it will be suitable for you, after porting to Python.

**Comment by pravic** [comment]
Closing for now as inactive.
